### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by sstopkin**
Fixed issue: ntpsync.js -> ntpSync.js

### CODE REVIEW

**Comment by nikolai3d** [comment]
Makes sense, thank you.

**Comment by sstopkin** [comment]
@nikolai3d can you please release new version https://www.npmjs.com/package/ntpsync ? Thank you!

**Comment by eaglevision20** [comment]
@nikolai3d, yes can you release the new version? We need this patch to deploy successfully to our Linux servers :) Thanks!!

**Comment by sstopkin** [comment]
@nikolai3d It seems that you broke library during publishing.
Pervious version (0.2.0) - file `ntpSync.js`, but packge.json - `ntpsync.js`
After my fix and publishing:
Current version (0.2.1) - file `ntpsync.js`, but packge.json - `ntpSync.js`
Can you please rename distribution file to ntpSync.js and use "ntpSync.js" in package.json?

**Comment by nikolai3d** [comment]
Right, the original ES6 was still old case.
Working on it.

**Comment by nikolai3d** [comment]
Merged and published (https://github.com/nikolai3d/ntpsync/pull/6) , let me know if this is still an issue. Apologies, no linux testing here, thanks for your help!

**Comment by sstopkin** [comment]
@nikolai3d It looks that issue is still present. File still named ntpsync.js instead ntpSync.js.

$ ls ntpsync/distribution 
ntpBurstRequest.js  ntpSingleRequest.js  ntpsync.js  ntpSyncMeasureDrift.js  ntpSyncTest.js

**Comment by nikolai3d** [comment]
Hmm weird.

**Comment by nikolai3d** [comment]
I see it too, version is 0.2.2, but the casing is still bad.

**Comment by nikolai3d** [comment]
@sstopkin I did a clean rebuild, and then clean reinstall as a dependency, to test. 
Had to do `npm cache clean` too. Please verify . THis is what I am seeing now:

image

**Comment by nikolai3d** [comment]
Version should be 0.2.3

**Comment by sstopkin** [comment]
@nikolai3d Now it is fine! Thank you!

**Pull request merged**
